"use server";
import { revalidatePath } from "next/cache";import{randomBytes}from"node:crypto";
import { z } from "zod";
import { requirePlatformRole } from "@/lib/auth/authorization";
import { createServerSupabaseClient } from "@/lib/supabase/server";
export type OpsState={message:string;success?:boolean;reference?:string;token?:string;emailDelivery?:string};
const text=z.string().trim().min(2); const uuid=z.uuid();
async function rpc(name:string,args:Record<string,unknown>,success:string):Promise<OpsState>{await requirePlatformRole(["afos_operations","afos_administrator"]);const db=await createServerSupabaseClient();const {error}=await db.rpc(name,args);if(error)return{message:error.message.includes("duplicate")?"This record already exists.":"This action could not be completed. Check the details and try again."};["/app","/app/capacity","/app/offers","/app/trips","/app/requests"].forEach((path)=>revalidatePath(path));return{message:success,success:true};}
export async function createCapacity(_:OpsState,f:FormData){const p=z.object({providerId:uuid,truck:text,trailer:text,driver:text,phone:z.string().trim().min(5),license:text,expiry:z.string(),size:text,quantity:z.coerce.number().int().min(1).max(100),from:z.string(),until:z.string(),pickup:z.string(),destination:z.string(),notes:z.string()}).safeParse({providerId:f.get("providerId"),truck:f.get("truck"),trailer:f.get("trailer"),driver:f.get("driver"),phone:f.get("phone"),license:f.get("license"),expiry:f.get("expiry")??"",size:f.get("size"),quantity:f.get("quantity"),from:f.get("from"),until:f.get("until"),pickup:f.get("pickup")??"",destination:f.get("destination")??"",notes:f.get("notes")??""});if(!p.success)return{message:"Complete the required vehicle, driver, size and availability details."};return rpc("create_provider_capacity",{target_provider_id:p.data.providerId,truck_registration:p.data.truck,trailer_registration:p.data.trailer,driver_name:p.data.driver,driver_phone:p.data.phone,driver_license:p.data.license,license_expires_on:p.data.expiry||null,container_size:p.data.size,capacity_quantity:p.data.quantity,available_from:new Date(p.data.from).toISOString(),available_until:new Date(p.data.until).toISOString(),pickup_area:p.data.pickup,destination_area:p.data.destination,notes:p.data.notes},"Capacity saved and ready for matching.");}
export async function sendOffer(_:OpsState,f:FormData){const p=z.object({requestId:uuid,capacityId:uuid,quantity:z.coerce.number().int().min(1),expires:z.string()}).safeParse({requestId:f.get("requestId"),capacityId:f.get("capacityId"),quantity:f.get("quantity"),expires:f.get("expires")});if(!p.success)return{message:"Choose a request, capacity record, quantity and expiry."};return rpc("send_provider_offer",{target_request_id:p.data.requestId,target_capacity_id:p.data.capacityId,offered_quantity:p.data.quantity,expires_at:new Date(p.data.expires).toISOString()},"Offer sent and recorded.");}
export async function respondOffer(_:OpsState,f:FormData){const p=z.object({offerId:uuid,decision:z.enum(["accepted","rejected"]),reason:z.string()}).safeParse({offerId:f.get("offerId"),decision:f.get("decision"),reason:f.get("reason")??""});if(!p.success)return{message:"Choose a response."};return rpc("record_offer_response",{target_offer_id:p.data.offerId,decision:p.data.decision,reason:p.data.reason},"Provider response recorded.");}
export async function allocateTrip(_:OpsState,f:FormData){const p=z.object({offerId:uuid,truckId:uuid,trailerId:uuid,driverId:uuid,start:z.string(),end:z.string()}).safeParse({offerId:f.get("offerId"),truckId:f.get("truckId"),trailerId:f.get("trailerId"),driverId:f.get("driverId"),start:f.get("start"),end:f.get("end")});if(!p.success)return{message:"Choose the accepted offer, resources and schedule."};return rpc("allocate_offer_and_create_trip",{target_offer_id:p.data.offerId,target_truck_id:p.data.truckId,target_trailer_id:p.data.trailerId,target_driver_id:p.data.driverId,scheduled_start:new Date(p.data.start).toISOString(),scheduled_end:new Date(p.data.end).toISOString()},"Resources allocated and trip created.");}
export async function createCompanyAvailability(_:OpsState,f:FormData){const p=z.object({providerId:uuid,size:text,quantity:z.coerce.number().int().min(1).max(100),from:z.string(),until:z.string(),area:z.string(),notes:z.string()}).safeParse({providerId:f.get("providerId"),size:f.get("size"),quantity:f.get("quantity"),from:f.get("from"),until:f.get("until"),area:f.get("area")??"",notes:f.get("notes")??""});if(!p.success)return{message:"Choose a verified company, container size, quantity and available dates."};return rpc("create_company_availability",{target_provider_id:p.data.providerId,size:p.data.size,available_quantity:p.data.quantity,start_date:p.data.from,end_date:p.data.until,area:p.data.area,notes:p.data.notes},"Company availability saved.");}
export async function assignCompany(_:OpsState,f:FormData){const p=z.object({requestId:uuid,availabilityId:uuid}).safeParse({requestId:f.get("requestId"),availabilityId:f.get("availabilityId")});if(!p.success)return{message:"Choose a request and an available company."};return rpc("assign_company_to_request",{target_request_id:p.data.requestId,target_availability_id:p.data.availabilityId},"Transport company assigned.");}
export async function regenerateTrackingAccess(_:OpsState,f:FormData):Promise<OpsState>{await requirePlatformRole(["afos_operations","afos_administrator"]);const p=z.object({requestId:uuid,verificationNote:z.string().trim().min(8)}).safeParse({requestId:f.get("requestId"),verificationNote:f.get("verificationNote")});if(!p.success)return{message:"Explain how you verified the customer, for example: confirmed phone number and route."};const token=randomBytes(24).toString("hex"),db=await createServerSupabaseClient();const{data,error}=await db.rpc("regenerate_guest_tracking_access",{target_request_id:p.data.requestId,new_tracking_token:token,verification_note:p.data.verificationNote});if(error)return{message:"Tracking access could not be regenerated. Confirm that database update 008 has been installed."};revalidatePath("/app/requests");return{message:"New tracking access created. The previous private code no longer works.",success:true,reference:data.reference,token};}
