import "server-only";

import { requirePlatformRole } from "@/lib/auth/authorization";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export type RequestSummary={id:string;reference:string;customer:string;containerSize:string;quantity:number;pickup:string;destination:string;requiredAt:string;contactName:string;contactPhone:string;status:string;containerNumber:string|null;contactEmail:string|null};
type Trip={id:string;reference:string;status:string;scheduledStart:string;scheduledEnd:string;provider:string;truck:string;trailer:string;driver:string;events:Array<{id:string;status:string;notes:string|null;occurredAt:string}>;exceptions:Array<{id:string;type:string;status:string;description:string;reportedAt:string;resolution:string|null}>;delivery:{outcome:string;deliveredAt:string|null;evidencePath:string|null;recipientName:string|null}|null};
export type RequestWorkspace=RequestSummary&{notes:string|null;cargoCategory:string|null;estimatedWeightKg:number|null;estimatedPrice:number|null;priceStatus:string;createdAt:string;compatibleAvailability:Array<{id:string;providerName:string;quantity:number;matchStatus:string;unavailableReason:string|null;nextAvailableAt:string|null}>;fleetPairs:Array<{providerId:string;providerName:string;truckId:string;truck:string;trailerId:string;trailer:string;driverId:string;driver:string}>;assignedUnits:number;trips:Trip[];activity:Array<{id:number;action:string;reason:string|null;occurredAt:string}>};

const one=<T>(value:T|T[])=>Array.isArray(value)?value[0]:value;

export async function listTransportRequests():Promise<RequestSummary[]>{
  await requirePlatformRole(["afos_operations","afos_administrator"]);const db=await createServerSupabaseClient();
  const{data,error}=await db.from("transport_requests").select("id,reference,container_size,quantity,pickup_location,destination_location,required_at,operational_contact_name,operational_contact_phone,contact_email,status,container_number,organizations!inner(name)").order("created_at",{ascending:false}).limit(100);
  if(error)throw new Error("Transport requests could not be loaded.");
  return(data??[]).map(r=>({id:r.id,reference:r.reference,customer:one(r.organizations)?.name??"Unknown customer",containerSize:r.container_size,quantity:r.quantity,pickup:r.pickup_location,destination:r.destination_location,requiredAt:r.required_at,contactName:r.operational_contact_name,contactPhone:r.operational_contact_phone,status:r.status,containerNumber:r.container_number,contactEmail:r.contact_email}));
}

export async function getRequestWorkspace(id:string):Promise<RequestWorkspace|null>{
  await requirePlatformRole(["afos_operations","afos_administrator"]);const db=await createServerSupabaseClient();
  const{data:r,error}=await db.from("transport_requests").select("id,reference,container_size,quantity,pickup_location,destination_location,required_at,operational_contact_name,operational_contact_phone,contact_email,status,container_number,notes,cargo_category,estimated_weight_kg,estimated_price,price_status,created_at,organizations!inner(name)").eq("id",id).maybeSingle();if(error||!r)return null;
  const[availability,activity,tripRows]=await Promise.all([
    db.rpc("provider_fleet_match_options",{target_request_id:id}),
    db.from("audit_events").select("id,action,reason,occurred_at").eq("entity_type","transport_request").eq("entity_id",id).order("occurred_at",{ascending:false}).limit(30),
    db.from("trips").select("id,reference,status,scheduled_start,scheduled_end,provider_id,organizations!inner(name),trucks!inner(registration_number),trailers!inner(registration_number),drivers!inner(full_name),allocations!inner(request_id)").eq("allocations.request_id",id).order("created_at"),
  ]);if(availability.error||activity.error||tripRows.error)throw new Error("Request workspace could not be loaded.");
  const trips:Trip[]=await Promise.all((tripRows.data??[]).map(async t=>{const[e,x,d]=await Promise.all([db.from("trip_status_events").select("id,to_status,notes,occurred_at").eq("trip_id",t.id).order("occurred_at"),db.from("exceptions").select("id,exception_type,status,description,reported_at,resolution").eq("trip_id",t.id).order("reported_at",{ascending:false}),db.from("deliveries").select("outcome,delivered_at,evidence_path,recipient_name").eq("trip_id",t.id).maybeSingle()]);if(e.error||x.error||d.error)throw new Error("Trip details could not be loaded.");return{id:t.id,reference:t.reference,status:t.status,scheduledStart:t.scheduled_start,scheduledEnd:t.scheduled_end,provider:one(t.organizations)?.name??"Unknown provider",truck:one(t.trucks)?.registration_number??"",trailer:one(t.trailers)?.registration_number??"",driver:one(t.drivers)?.full_name??"",events:(e.data??[]).map(v=>({id:v.id,status:v.to_status,notes:v.notes,occurredAt:v.occurred_at})),exceptions:(x.data??[]).map(v=>({id:v.id,type:v.exception_type,status:v.status,description:v.description,reportedAt:v.reported_at,resolution:v.resolution})),delivery:d.data?{outcome:d.data.outcome,deliveredAt:d.data.delivered_at,evidencePath:d.data.evidence_path,recipientName:d.data.recipient_name}:null}}));
  const assignedIds=new Set(trips.flatMap(t=>[t.truck,t.trailer]));
  const pairResults=await Promise.all((availability.data??[]).filter((v:{match_status:string})=>v.match_status==="available").map(async(v:{provider_id:string;provider_name:string})=>{const p=await db.rpc("available_fleet_pairs",{target_request_id:id,target_provider_id:v.provider_id,check_start:r.required_at,check_end:new Date(new Date(r.required_at).getTime()+86400000).toISOString()});if(p.error)throw new Error("Available fleet could not be loaded.");return(p.data??[]).filter((q:{truck_registration:string;trailer_registration:string})=>!assignedIds.has(q.truck_registration)&&!assignedIds.has(q.trailer_registration)).map((q:{truck_id:string;truck_registration:string;trailer_id:string;trailer_registration:string;driver_id:string;driver_name:string})=>({providerId:v.provider_id,providerName:v.provider_name,truckId:q.truck_id,truck:q.truck_registration,trailerId:q.trailer_id,trailer:q.trailer_registration,driverId:q.driver_id,driver:q.driver_name}))}));
  return{id:r.id,reference:r.reference,customer:one(r.organizations)?.name??"Unknown customer",containerSize:r.container_size,quantity:r.quantity,pickup:r.pickup_location,destination:r.destination_location,requiredAt:r.required_at,contactName:r.operational_contact_name,contactPhone:r.operational_contact_phone,status:r.status,containerNumber:r.container_number,contactEmail:r.contact_email,notes:r.notes,cargoCategory:r.cargo_category,estimatedWeightKg:r.estimated_weight_kg,estimatedPrice:r.estimated_price,priceStatus:r.price_status,createdAt:r.created_at,compatibleAvailability:(availability.data??[]).map((v:{provider_id:string;provider_name:string;available_units:number;match_status:string;unavailable_reason:string|null;next_available_at:string|null})=>({id:v.provider_id,providerName:v.provider_name,quantity:v.available_units,matchStatus:v.match_status,unavailableReason:v.unavailable_reason,nextAvailableAt:v.next_available_at})),fleetPairs:pairResults.flat(),assignedUnits:trips.length,trips,activity:(activity.data??[]).map(v=>({id:v.id,action:v.action,reason:v.reason,occurredAt:v.occurred_at}))};
}
