import "server-only"; import {requirePlatformRole} from "@/lib/auth/authorization"; import {createServerSupabaseClient} from "@/lib/supabase/server";
export async function operationalData(){await requirePlatformRole(["afos_operations","afos_administrator"]);const db=await createServerSupabaseClient();const [providers,capacity,requests,offers,trucks,trailers,drivers,trips]=await Promise.all([
db.from("organizations").select("id,name,provider_verifications!inner(status)").eq("organization_type","transport_provider").eq("provider_verifications.status","verified"),
db.from("capacity_declarations").select("id,provider_id,container_size,quantity,available_from,available_until,pickup_area,destination_area,organizations!inner(name)").is("withdrawn_at",null).order("created_at",{ascending:false}),
db.from("transport_requests").select("id,reference,container_size,quantity,pickup_location,destination_location,required_at,status").in("status",["submitted","matching","matched"]),
db.from("provider_offers").select("id,request_id,provider_id,quantity,status,expires_at,transport_requests!inner(reference),organizations!inner(name)").order("created_at",{ascending:false}),
db.from("trucks").select("id,provider_id,registration_number,status").eq("status","active"),db.from("trailers").select("id,provider_id,registration_number,container_size,status").eq("status","active"),db.from("drivers").select("id,provider_id,full_name,license_expires_on,status").eq("status","active"),
db.from("trips").select("id,reference,status,scheduled_start,scheduled_end,organizations!inner(name),allocations!inner(transport_requests!inner(reference)),trucks!inner(registration_number),trailers!inner(registration_number),drivers!inner(full_name)").order("created_at",{ascending:false})]);
for(const result of [providers,capacity,requests,offers,trucks,trailers,drivers,trips])if(result.error)throw new Error("Operational data could not be loaded.");
const one=<T>(value:T|T[])=>Array.isArray(value)?value[0]:value;
return{providers:providers.data??[],capacity:(capacity.data??[]).map(x=>({...x,organizations:one(x.organizations)})),requests:requests.data??[],offers:(offers.data??[]).map(x=>({...x,transport_requests:one(x.transport_requests),organizations:one(x.organizations)})),trucks:trucks.data??[],trailers:trailers.data??[],drivers:drivers.data??[],trips:(trips.data??[]).map(x=>({...x,organizations:one(x.organizations),allocations:one(x.allocations),trucks:one(x.trucks),trailers:one(x.trailers),drivers:one(x.drivers)}))};}
