import Link from "next/link";import{notFound}from"next/navigation";
import{advanceTrip,assignRequestFleet,completeTripDelivery,confirmRequestPrice,regenerateTrackingAccess,reportTripException,resolveTripException}from"@/app/actions/operations";
import{AppShell}from"@/components/app/app-shell";import{FleetAssignmentForm}from"@/components/requests/fleet-assignment-form";import{RecoveryForm}from"@/components/requests/recovery-form";import{PriceForm}from"@/components/requests/request-workspace-forms";import{DeliveryForm,ExceptionForm,ResolveExceptionForm,TripProgressForm}from"@/components/requests/trip-workspace-forms";import{requireUser}from"@/lib/auth/session";import{getRequestWorkspace}from"@/lib/requests/data";
export const dynamic="force-dynamic";
const human=(s:string)=>s.replaceAll("_"," ");
function Heading({number,title,copy}:{number:string;title:string;copy:string}){return <div className="workspace-section-heading"><span>{number}</span><div><h2>{title}</h2><p>{copy}</p></div></div>}
export default async function RequestDetailPage({params}:{params:Promise<{id:string}>}){const user=await requireUser(),r=await getRequestWorkspace((await params).id);if(!r)notFound();const date=new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}),remaining=Math.max(0,r.quantity-r.assignedUnits);return <AppShell active="Requests" email={user.email}>
<Link className="workspace-back" href="/app/requests">← Back to requests</Link><header className="workspace-heading"><div><span className="operations-kicker">Request workspace</span><h1>{r.reference}</h1><p>{r.customer}</p></div><span className={`status-chip status-${r.status}`}>{human(r.status)}</span></header>
<section className="workspace-summary"><div><span>Container</span><strong>{r.quantity} × {r.containerSize}</strong><small>{r.containerNumber??"Number not supplied"}</small></div><div><span>Route</span><strong>{r.pickup} → {r.destination}</strong><small>Pickup {date.format(new Date(r.requiredAt))}</small></div><div><span>Customer</span><strong>{r.contactName}</strong><a href={`tel:${r.contactPhone}`}>{r.contactPhone}</a>{r.contactEmail&&<a href={`mailto:${r.contactEmail}`}>{r.contactEmail}</a>}</div><div><span>Fleet progress</span><strong>{r.assignedUnits} of {r.quantity} assigned</strong><small>{remaining?`${remaining} still needs fleet`:"All fleet reserved"}</small></div></section>
<div className="workspace-grid"><section className="workspace-card"><Heading number="01" title="Confirm the price" copy="Set the amount the customer sees while tracking."/><div className="workspace-current"><span>Current price</span><strong>{r.estimatedPrice!=null?`SLE ${Number(r.estimatedPrice).toLocaleString()}`:"Not confirmed"}</strong><small>{human(r.priceStatus)}</small></div><PriceForm requestId={r.id} currentPrice={r.estimatedPrice} action={confirmRequestPrice}/></section>
<section className="workspace-card primary fleet-assignment-card"><Heading number="02" title="Find and assign fleet" copy="Everything needed to match this request is here—no provider-page detour."/><div className="assignment-progress"><strong>{r.assignedUnits} assigned</strong><span>{remaining} remaining</span></div>{remaining>0?<><div className="match-options">{r.compatibleAvailability.map(x=><article key={x.id} className={`match-option ${x.matchStatus}`}><div><span className={`status-chip status-${x.matchStatus}`}>{human(x.matchStatus)}</span><strong>{x.providerName}</strong><small>{x.quantity} compatible unit{x.quantity===1?"":"s"} available</small></div>{x.matchStatus!=="available"&&<p>{x.unavailableReason??"No compatible fleet is ready."}{x.nextAvailableAt?` Next expected: ${date.format(new Date(x.nextAvailableAt))}.`:" No confirmed return date yet."}</p>}</article>)}</div>{r.fleetPairs.length?<FleetAssignmentForm requestId={r.id} quantity={r.quantity} alreadyAssigned={r.assignedUnits} pairs={r.fleetPairs} action={assignRequestFleet}/>:<div className="workspace-empty"><strong>No compatible fleet is ready for this pickup</strong><p>The availability cards show why and the next recorded date where known. The request remains open.</p></div>}</>:<div className="assignment-success"><span>Assignment complete</span><strong>All {r.quantity} fleet units are reserved</strong><small>The trips below are ready for operations.</small></div>}</section>
<section className="workspace-card trip-card"><Heading number="03" title="Run assigned trips" copy="Each container has its own provider, truck, trailer and driver."/>{r.trips.length?<div className="request-trip-list">{r.trips.map((trip,index)=><article className="request-trip" key={trip.id}><div className="trip-identity"><span className={`status-chip status-${trip.status}`}>{human(trip.status)}</span><strong>Unit {index+1}: {trip.reference}</strong><small>{trip.provider} · Truck {trip.truck} · Trailer {trip.trailer}</small><small>Driver {trip.driver} · {date.format(new Date(trip.scheduledStart))} → {date.format(new Date(trip.scheduledEnd))}</small></div><ol className="trip-timeline">{trip.events.map(e=><li key={e.id}><strong>{human(e.status)}</strong><span>{date.format(new Date(e.occurredAt))}</span>{e.notes&&<p>{e.notes}</p>}</li>)}</ol><TripProgressForm tripId={trip.id} status={trip.status} action={advanceTrip}/><details className="inline-details"><summary>Report or review problems</summary><ExceptionForm tripId={trip.id} requestId={r.id} action={reportTripException}/>{trip.exceptions.map(e=><div className="exception-list" key={e.id}><article><span className={`status-chip status-${e.status}`}>{e.status}</span><strong>{human(e.type)}</strong><p>{e.description}</p>{e.status==="open"?<ResolveExceptionForm exceptionId={e.id} action={resolveTripException}/>:e.resolution&&<p>Resolution: {e.resolution}</p>}</article></div>)}</details>{trip.delivery?<div className="assignment-success"><span>Delivered</span><strong>Received by {trip.delivery.recipientName}</strong></div>:trip.status==="at_destination"?<DeliveryForm tripId={trip.id} action={completeTripDelivery}/>:<p className="workspace-muted">Proof of delivery opens when this unit reaches its destination.</p>}</article>)}</div>:<p className="workspace-muted">Select fleet above to create and reserve the trips automatically.</p>}</section>
<section className="workspace-card"><Heading number="04" title="Activity history" copy="Important actions recorded for accountability."/>{r.activity.length?<ol className="activity-list">{r.activity.map(x=><li key={x.id}><strong>{human(x.action)}</strong><span>{date.format(new Date(x.occurredAt))}</span>{x.reason&&<p>{x.reason}</p>}</li>)}</ol>:<p className="workspace-muted">No activity yet.</p>}</section></div>
<details className="workspace-recovery"><summary>Customer lost their receipt or tracking code</summary><p>Verify the caller using the saved phone number and route before replacement.</p><RecoveryForm requestId={r.id} action={regenerateTrackingAccess}/></details></AppShell>}
