begin;

alter table public.organizations add column if not exists provider_kind text check(provider_kind in('company','individual_owner'));
alter table public.organizations add column if not exists declared_vehicle_count integer check(declared_vehicle_count is null or declared_vehicle_count>=0);
alter table public.organizations add column if not exists primary_contact_email text;
alter table public.organizations add column if not exists operating_areas text;
alter table public.trucks add column if not exists insurance_expires_on date;
alter table public.trucks add column if not exists roadworthiness_expires_on date;
alter table public.trucks add column if not exists unavailable_until date;
alter table public.trucks add column if not exists unavailable_reason text;
alter table public.trailers add column if not exists insurance_expires_on date;
alter table public.trailers add column if not exists roadworthiness_expires_on date;
alter table public.trailers add column if not exists unavailable_until date;
alter table public.trailers add column if not exists unavailable_reason text;
alter table public.transport_requests add column if not exists availability_status text not null default 'checking' check(availability_status in('checking','available','available_later','unavailable'));
alter table public.transport_requests add column if not exists alternative_available_at timestamptz;
alter table public.transport_requests add column if not exists alternative_response text check(alternative_response in('pending','accepted','declined'));
alter table public.transport_requests add column if not exists original_required_at timestamptz;

create unique index if not exists trucks_registration_global_unique on public.trucks(upper(trim(registration_number)));
create unique index if not exists trailers_registration_global_unique on public.trailers(upper(trim(registration_number)));

create or replace function public.create_transport_provider_v2(provider_name text,provider_kind text,registration_number text,contact_name text,contact_phone text,contact_email text,declared_vehicles integer,operating_areas text) returns uuid language plpgsql security invoker set search_path='' as $provider$
declare provider_id uuid;
begin
if not(public.has_platform_role('afos_operations') or public.has_platform_role('afos_administrator')) then raise exception 'Not authorized';end if;
if provider_kind not in('company','individual_owner') or char_length(trim(provider_name))<2 or char_length(trim(contact_name))<2 or char_length(trim(contact_phone))<5 or declared_vehicles<1 then raise exception 'Provider details incomplete';end if;
if provider_kind='company' and char_length(trim(registration_number))<2 then raise exception 'Company registration number required';end if;
insert into public.organizations(name,organization_type,registration_number,primary_contact_name,primary_contact_phone,primary_contact_email,provider_kind,declared_vehicle_count,operating_areas) values(trim(provider_name),'transport_provider',nullif(trim(registration_number),''),trim(contact_name),trim(contact_phone),nullif(trim(contact_email),''),provider_kind,declared_vehicles,nullif(trim(operating_areas),'')) returning id into provider_id;
insert into public.provider_verifications(provider_id,status) values(provider_id,'draft');
insert into public.audit_events(actor_id,organization_id,action,entity_type,entity_id,after_data) values(auth.uid(),provider_id,'provider.created','organization',provider_id,jsonb_build_object('kind',provider_kind,'declared_vehicles',declared_vehicles));return provider_id;end;$provider$;

create or replace function public.register_provider_vehicle(target_provider_id uuid,vehicle_kind text,registration text,container_size text,insurance_expiry date,roadworthiness_expiry date) returns uuid language plpgsql security invoker set search_path='' as $vehicle$
declare result uuid;verification public.verification_status;
begin
if not(public.has_platform_role('afos_operations') or public.has_platform_role('afos_administrator')) then raise exception 'Not authorized';end if;if vehicle_kind not in('truck','trailer') or char_length(trim(registration))<2 then raise exception 'Vehicle details incomplete';end if;select status into verification from public.provider_verifications where provider_id=target_provider_id;if verification is null then raise exception 'Provider not found';end if;
if vehicle_kind='truck' then insert into public.trucks(provider_id,registration_number,insurance_expires_on,roadworthiness_expires_on) values(target_provider_id,upper(trim(registration)),insurance_expiry,roadworthiness_expiry) returning id into result;else if char_length(trim(container_size))<2 then raise exception 'Trailer container size required';end if;insert into public.trailers(provider_id,registration_number,container_size,insurance_expires_on,roadworthiness_expires_on) values(target_provider_id,upper(trim(registration)),trim(container_size),insurance_expiry,roadworthiness_expiry) returning id into result;end if;
insert into public.audit_events(actor_id,organization_id,action,entity_type,entity_id,after_data) values(auth.uid(),target_provider_id,'vehicle.registered',vehicle_kind,result,jsonb_build_object('registration',upper(trim(registration))));return result;end;$vehicle$;

create or replace function public.set_vehicle_availability(vehicle_kind text,vehicle_id uuid,next_status text,available_again date,reason text) returns void language plpgsql security invoker set search_path='' as $availability$
declare provider uuid;
begin if not(public.has_platform_role('afos_operations') or public.has_platform_role('afos_administrator')) then raise exception 'Not authorized';end if;if vehicle_kind not in('truck','trailer') or next_status not in('active','inactive') then raise exception 'Invalid availability';end if;if next_status='inactive' and (available_again is null or char_length(trim(reason))<3) then raise exception 'Return date and reason required';end if;
if vehicle_kind='truck' then update public.trucks set status=next_status::public.record_status,unavailable_until=case when next_status='inactive' then available_again else null end,unavailable_reason=case when next_status='inactive' then trim(reason) else null end,updated_at=now() where id=vehicle_id returning provider_id into provider;else update public.trailers set status=next_status::public.record_status,unavailable_until=case when next_status='inactive' then available_again else null end,unavailable_reason=case when next_status='inactive' then trim(reason) else null end,updated_at=now() where id=vehicle_id returning provider_id into provider;end if;if provider is null then raise exception 'Vehicle not found';end if;insert into public.audit_events(actor_id,organization_id,action,entity_type,entity_id,reason,after_data) values(auth.uid(),provider,'vehicle.availability_updated',vehicle_kind,vehicle_id,nullif(trim(reason),''),jsonb_build_object('status',next_status,'available_again',available_again));end;$availability$;

create or replace function public.assess_request_vehicle_capacity(target_request_id uuid) returns jsonb language plpgsql security invoker set search_path='' as $assess$
declare req public.transport_requests%rowtype;available_trucks integer;available_trailers integer;available_count integer;next_date timestamptz;
begin select * into req from public.transport_requests where id=target_request_id for update;if req.id is null then raise exception 'Request not found';end if;
select count(*) into available_trucks from public.trucks tr join public.provider_verifications pv on pv.provider_id=tr.provider_id and pv.status='verified' where tr.status='active' and (tr.unavailable_until is null or tr.unavailable_until<req.required_at::date) and (tr.insurance_expires_on is null or tr.insurance_expires_on>=req.required_at::date) and (tr.roadworthiness_expires_on is null or tr.roadworthiness_expires_on>=req.required_at::date) and not exists(select 1 from public.trips t where t.truck_id=tr.id and t.status not in('completed','failed','cancelled') and tstzrange(t.scheduled_start,t.scheduled_end,'[)') && tstzrange(req.required_at,req.required_at+interval '1 day','[)'));
select count(*) into available_trailers from public.trailers tr join public.provider_verifications pv on pv.provider_id=tr.provider_id and pv.status='verified' where tr.status='active' and (tr.unavailable_until is null or tr.unavailable_until<req.required_at::date) and lower(trim(tr.container_size))=lower(trim(req.container_size)) and (tr.insurance_expires_on is null or tr.insurance_expires_on>=req.required_at::date) and (tr.roadworthiness_expires_on is null or tr.roadworthiness_expires_on>=req.required_at::date) and not exists(select 1 from public.trips t where t.trailer_id=tr.id and t.status not in('completed','failed','cancelled') and tstzrange(t.scheduled_start,t.scheduled_end,'[)') && tstzrange(req.required_at,req.required_at+interval '1 day','[)'));
available_count:=least(available_trucks,available_trailers);
if available_count>=req.quantity then update public.transport_requests set availability_status='available',alternative_available_at=null,alternative_response=null where id=req.id;return jsonb_build_object('status','available','available_count',available_count);end if;
select min(t.scheduled_end) into next_date from public.trips t join public.trailers tr on tr.id=t.trailer_id join public.provider_verifications pv on pv.provider_id=tr.provider_id and pv.status='verified' where t.status not in('completed','failed','cancelled') and lower(trim(tr.container_size))=lower(trim(req.container_size)) and t.scheduled_end>req.required_at;
if next_date is not null then update public.transport_requests set availability_status='available_later',alternative_available_at=next_date,alternative_response='pending',original_required_at=coalesce(original_required_at,required_at) where id=req.id;return jsonb_build_object('status','available_later','available_at',next_date);end if;
update public.transport_requests set availability_status='checking',alternative_available_at=null,alternative_response=null where id=req.id;return jsonb_build_object('status','checking');end;$assess$;

create or replace function public.compatible_fleet_providers(target_request_id uuid) returns table(provider_id uuid,provider_name text,available_units integer,total_units integer,next_available_at timestamptz) language plpgsql security invoker set search_path='' as $fleet$
begin
if not(public.has_platform_role('afos_operations') or public.has_platform_role('afos_administrator')) then raise exception 'Not authorized';end if;
return query with req as(select * from public.transport_requests where id=target_request_id), providers as(select o.id,o.name from public.organizations o join public.provider_verifications pv on pv.provider_id=o.id and pv.status='verified' where o.organization_type='transport_provider'), truck_counts as(select p.id,count(t.id)::integer total,count(t.id) filter(where t.status='active' and (t.unavailable_until is null or t.unavailable_until<r.required_at::date) and (t.insurance_expires_on is null or t.insurance_expires_on>=r.required_at::date) and (t.roadworthiness_expires_on is null or t.roadworthiness_expires_on>=r.required_at::date) and not exists(select 1 from public.trips x where x.truck_id=t.id and x.status not in('completed','failed','cancelled') and tstzrange(x.scheduled_start,x.scheduled_end,'[)')&&tstzrange(r.required_at,r.required_at+interval '1 day','[)')))::integer available from providers p cross join req r left join public.trucks t on t.provider_id=p.id group by p.id), trailer_counts as(select p.id,count(t.id)::integer total,count(t.id) filter(where t.status='active' and lower(trim(t.container_size))=lower(trim(r.container_size)) and (t.unavailable_until is null or t.unavailable_until<r.required_at::date) and (t.insurance_expires_on is null or t.insurance_expires_on>=r.required_at::date) and (t.roadworthiness_expires_on is null or t.roadworthiness_expires_on>=r.required_at::date) and not exists(select 1 from public.trips x where x.trailer_id=t.id and x.status not in('completed','failed','cancelled') and tstzrange(x.scheduled_start,x.scheduled_end,'[)')&&tstzrange(r.required_at,r.required_at+interval '1 day','[)')))::integer available from providers p cross join req r left join public.trailers t on t.provider_id=p.id group by p.id)
select p.id,p.name,least(tc.available,lc.available),least(tc.total,lc.total),null::timestamptz from providers p join truck_counts tc on tc.id=p.id join trailer_counts lc on lc.id=p.id where least(tc.available,lc.available)>0 order by least(tc.available,lc.available) desc,p.name;
end;$fleet$;

create or replace function public.assign_fleet_provider_to_request(target_request_id uuid,target_provider_id uuid) returns uuid language plpgsql security invoker set search_path='' as $assign_fleet$
declare assignment_id uuid;needed integer;available integer;
begin if not(public.has_platform_role('afos_operations') or public.has_platform_role('afos_administrator')) then raise exception 'Not authorized';end if;select quantity into needed from public.transport_requests where id=target_request_id for update;select available_units into available from public.compatible_fleet_providers(target_request_id) where provider_id=target_provider_id;if available is null or available<needed then raise exception 'This provider no longer has enough compatible vehicles';end if;if exists(select 1 from public.company_assignments where request_id=target_request_id and status<>'cancelled') then raise exception 'Request already assigned';end if;insert into public.company_assignments(request_id,provider_id,status,assigned_by) values(target_request_id,target_provider_id,'allocated',auth.uid()) returning id into assignment_id;update public.transport_requests set status='matched',availability_status='available',updated_at=now() where id=target_request_id;insert into public.audit_events(actor_id,organization_id,action,entity_type,entity_id,after_data) values(auth.uid(),target_provider_id,'company.assigned_from_fleet','transport_request',target_request_id,jsonb_build_object('available_units',available));return assignment_id;end;$assign_fleet$;

create or replace function public.respond_to_alternative_date(request_reference text,tracking_token text,decision text) returns jsonb language plpgsql security definer set search_path='' as $respond$
declare req public.transport_requests%rowtype;
begin if decision not in('accepted','declined') then raise exception 'Invalid decision';end if;select * into req from public.transport_requests where upper(reference)=upper(trim(request_reference)) and tracking_token_hash=encode(extensions.digest(tracking_token,'sha256'),'hex') for update;if req.id is null or req.availability_status<>'available_later' or req.alternative_response<>'pending' then raise exception 'Alternative is not available';end if;update public.transport_requests set alternative_response=decision,required_at=case when decision='accepted' then alternative_available_at else required_at end,updated_at=now() where id=req.id;insert into public.audit_events(organization_id,action,entity_type,entity_id,after_data) values(req.organization_id,'transport_request.alternative_'||decision,'transport_request',req.id,jsonb_build_object('alternative_available_at',req.alternative_available_at));return jsonb_build_object('reference',req.reference,'decision',decision);end;$respond$;

grant execute on function public.create_transport_provider_v2(text,text,text,text,text,text,integer,text) to authenticated;
grant execute on function public.register_provider_vehicle(uuid,text,text,text,date,date) to authenticated;
grant execute on function public.set_vehicle_availability(text,uuid,text,date,text) to authenticated;
grant execute on function public.assess_request_vehicle_capacity(uuid) to authenticated;
grant execute on function public.compatible_fleet_providers(uuid) to authenticated;
grant execute on function public.assign_fleet_provider_to_request(uuid,uuid) to authenticated;
grant execute on function public.respond_to_alternative_date(text,text,text) to anon,authenticated;
create or replace function public.assess_guest_request_capacity(request_reference text,tracking_token text) returns jsonb language plpgsql security definer set search_path='' as $guest_assess$
declare resolved_request_id uuid;result jsonb;begin select id into resolved_request_id from public.transport_requests where upper(reference)=upper(trim(request_reference)) and tracking_token_hash=encode(extensions.digest(tracking_token,'sha256'),'hex');if resolved_request_id is null then raise exception 'Request not found';end if;select public.assess_request_vehicle_capacity(resolved_request_id) into result;return result;end;$guest_assess$;
create or replace function public.track_guest_request(request_reference text,tracking_token text) returns jsonb language plpgsql security definer set search_path='' as $track_capacity$
declare result jsonb;begin select jsonb_build_object('reference',r.reference,'status',r.status,'container_size',r.container_size,'quantity',r.quantity,'pickup',r.pickup_location,'destination',r.destination_location,'required_at',r.required_at,'estimated_price',r.estimated_price,'price_status',r.price_status,'provider',o.name,'trip_reference',t.reference,'trip_status',t.status,'scheduled_start',t.scheduled_start,'scheduled_end',t.scheduled_end,'delivered_at',t.delivered_at,'delivery_recipient',d.recipient_name,'open_exception',ex.exception_type,'availability_status',r.availability_status,'alternative_available_at',r.alternative_available_at,'alternative_response',r.alternative_response,'trip_events',coalesce((select jsonb_agg(jsonb_build_object('status',e.to_status,'notes',e.notes,'occurred_at',e.occurred_at) order by e.occurred_at) from public.trip_status_events e where e.trip_id=t.id),'[]'::jsonb)) into result from public.transport_requests r left join public.company_assignments a on a.request_id=r.id left join public.organizations o on o.id=a.provider_id left join public.allocations al on al.request_id=r.id left join public.trips t on t.allocation_id=al.id left join public.deliveries d on d.trip_id=t.id left join lateral(select exception_type from public.exceptions where trip_id=t.id and status='open' order by reported_at desc limit 1) ex on true where upper(r.reference)=upper(trim(request_reference)) and r.tracking_token_hash=encode(extensions.digest(tracking_token,'sha256'),'hex') limit 1;return result;end;$track_capacity$;
grant execute on function public.assess_guest_request_capacity(text,text) to anon,authenticated;
grant execute on function public.track_guest_request(text,text) to anon,authenticated;
commit;
