create or replace function public.submit_guest_transport_request(customer_name text,container_size text,container_quantity integer,pickup_location text,destination_location text,required_at timestamptz,contact_name text,contact_phone text,contact_email text default '',cargo_category text default '',estimated_weight_kg numeric default null,container_number text default '',notes text default '',tracking_token text default '') returns jsonb language plpgsql security definer set search_path='' as $fn$
declare org_id uuid;req_id uuid;ref text;tariff public.route_tariffs%rowtype;estimate numeric;
begin
if char_length(trim(customer_name))<2 or char_length(trim(container_size))<2 or container_quantity<1 or container_quantity>100 or char_length(trim(pickup_location))<2 or char_length(trim(destination_location))<2 or char_length(trim(contact_name))<2 or char_length(trim(contact_phone))<5 or char_length(tracking_token)<32 then raise exception 'Required information is incomplete';end if;
insert into public.organizations(name,organization_type,primary_contact_name,primary_contact_phone) values(trim(customer_name),'customer',trim(contact_name),trim(contact_phone)) returning id into org_id;
select * into tariff from public.route_tariffs where active=true and lower(trim(route_tariffs.container_size))=lower(trim(submit_guest_transport_request.container_size)) and lower(trim(pickup_location)) like '%'||lower(pickup_pattern)||'%' and lower(trim(destination_location)) like '%'||lower(destination_pattern)||'%' limit 1;
if tariff.id is not null then estimate:=tariff.base_price+greatest(container_quantity-1,0)*tariff.additional_container_price;end if;
ref:='REQ-'||to_char(now(),'YYMMDD')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,6));
insert into public.transport_requests(reference,organization_id,requested_by,container_size,quantity,pickup_location,destination_location,required_at,operational_contact_name,operational_contact_phone,status,movement_type,cargo_category,estimated_weight_kg,container_number,notes,tracking_token_hash,estimated_price,price_status,contact_email) values(ref,org_id,null,trim(container_size),container_quantity,trim(pickup_location),trim(destination_location),required_at,trim(contact_name),trim(contact_phone),'submitted','other',nullif(trim(cargo_category),''),estimated_weight_kg,nullif(upper(trim(container_number)),''),nullif(trim(notes),''),encode(extensions.digest(tracking_token,'sha256'),'hex'),estimate,case when estimate is null then 'confirmation_required' else 'estimated' end,nullif(trim(contact_email),'')) returning id into req_id;
return jsonb_build_object('reference',ref,'estimated_price',estimate,'currency',coalesce(tariff.currency,'SLE'),'price_status',case when estimate is null then 'confirmation_required' else 'estimated' end);
end;$fn$;
grant execute on function public.submit_guest_transport_request(text,text,integer,text,text,timestamptz,text,text,text,text,numeric,text,text,text) to anon,authenticated;
