begin;
alter table public.deliveries add column if not exists recipient_name text;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('delivery-evidence','delivery-evidence',false,8388608,array['image/jpeg','image/png','application/pdf']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists delivery_evidence_operations on storage.objects;
create policy delivery_evidence_operations on storage.objects for all to authenticated using(bucket_id='delivery-evidence' and (public.has_platform_role('afos_operations') or public.has_platform_role('afos_administrator'))) with check(bucket_id='delivery-evidence' and (public.has_platform_role('afos_operations') or public.has_platform_role('afos_administrator')));

create or replace function public.create_trip_for_company_assignment(target_request_id uuid,target_truck_id uuid,target_trailer_id uuid,target_driver_id uuid,scheduled_start timestamptz,scheduled_end timestamptz) returns uuid language plpgsql security invoker set search_path='' as $create_trip$
declare a public.company_assignments%rowtype;allocation_id uuid;trip_id uuid;trip_reference text;synthetic_offer uuid;
begin
if not(public.has_platform_role('afos_operations') or public.has_platform_role('afos_administrator')) then raise exception 'Not authorized';end if;select * into a from public.company_assignments where request_id=target_request_id and status<>'cancelled' for update;if a.id is null then raise exception 'Company assignment required';end if;if scheduled_end<=scheduled_start then raise exception 'Trip schedule is invalid';end if;if exists(select 1 from public.allocations where request_id=target_request_id) then raise exception 'Trip already exists';end if;if not exists(select 1 from public.trucks where id=target_truck_id and provider_id=a.provider_id and status='active') or not exists(select 1 from public.trailers where id=target_trailer_id and provider_id=a.provider_id and status='active') or not exists(select 1 from public.drivers where id=target_driver_id and provider_id=a.provider_id and status='active' and (license_expires_on is null or license_expires_on>=scheduled_start::date)) then raise exception 'Resources are not eligible';end if;
insert into public.provider_offers(request_id,provider_id,quantity,status,sent_at,responded_at,expires_at,created_by) select r.id,a.provider_id,r.quantity,'accepted',now(),now(),scheduled_start,auth.uid() from public.transport_requests r where r.id=target_request_id returning id into synthetic_offer;insert into public.allocations(request_id,offer_id,provider_id,quantity,allocated_by) select r.id,synthetic_offer,a.provider_id,r.quantity,auth.uid() from public.transport_requests r where r.id=target_request_id returning id into allocation_id;trip_reference:='TRIP-'||to_char(now(),'YYMMDD')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,6));insert into public.trips(reference,allocation_id,provider_id,truck_id,trailer_id,driver_id,scheduled_start,scheduled_end) values(trip_reference,allocation_id,a.provider_id,target_truck_id,target_trailer_id,target_driver_id,scheduled_start,scheduled_end) returning id into trip_id;insert into public.trip_status_events(trip_id,to_status,notes,changed_by) values(trip_id,'assigned','Resources assigned by AFOS Operations',auth.uid());update public.transport_requests set status='allocated',updated_at=now() where id=target_request_id;insert into public.audit_events(actor_id,organization_id,action,entity_type,entity_id,after_data) values(auth.uid(),a.provider_id,'trip.created','transport_request',target_request_id,jsonb_build_object('trip_id',trip_id,'reference',trip_reference));return trip_id;end;$create_trip$;

create or replace function public.advance_trip_status(target_trip_id uuid,next_status text,status_note text) returns void language plpgsql security invoker set search_path='' as $advance$
declare t public.trips%rowtype;request_id uuid;allowed boolean;
begin
if not(public.has_platform_role('afos_operations') or public.has_platform_role('afos_administrator')) then raise exception 'Not authorized';end if;if char_length(trim(status_note))<3 then raise exception 'Status note required';end if;select * into t from public.trips where id=target_trip_id for update;select a.request_id into request_id from public.allocations a where a.id=t.allocation_id;allowed:=case t.status::text when 'assigned' then next_status='acknowledged' when 'acknowledged' then next_status='ready' when 'ready' then next_status='dispatched' when 'dispatched' then next_status='at_pickup' when 'at_pickup' then next_status='in_transit' when 'in_transit' then next_status='at_destination' else false end;if not allowed then raise exception 'Invalid trip status transition';end if;update public.trips set status=next_status::public.trip_status where id=target_trip_id;insert into public.trip_status_events(trip_id,from_status,to_status,notes,changed_by) values(target_trip_id,t.status,next_status::public.trip_status,trim(status_note),auth.uid());update public.transport_requests set status='in_progress',updated_at=now() where id=request_id and next_status in('dispatched','at_pickup','in_transit','at_destination');insert into public.audit_events(actor_id,organization_id,action,entity_type,entity_id,reason,before_data,after_data) values(auth.uid(),t.provider_id,'trip.status_updated','transport_request',request_id,trim(status_note),jsonb_build_object('trip_status',t.status),jsonb_build_object('trip_status',next_status));end;$advance$;

create or replace function public.report_trip_exception(target_trip_id uuid,target_request_id uuid,exception_kind text,details text,impact text,replacement_required boolean) returns uuid language plpgsql security invoker set search_path='' as $exception$
declare result uuid;provider uuid;
begin if not(public.has_platform_role('afos_operations') or public.has_platform_role('afos_administrator')) then raise exception 'Not authorized';end if;if exception_kind not in('delay','driver_no_show','vehicle_breakdown','container_not_released','missing_documents','other') or char_length(trim(details))<5 then raise exception 'Invalid exception';end if;select provider_id into provider from public.trips where id=target_trip_id;insert into public.exceptions(request_id,trip_id,exception_type,description,operational_impact,replacement_capacity_required,reported_by) values(target_request_id,target_trip_id,exception_kind,trim(details),nullif(trim(impact),''),replacement_required,auth.uid()) returning id into result;insert into public.audit_events(actor_id,organization_id,action,entity_type,entity_id,reason,after_data) values(auth.uid(),provider,'trip.exception_reported','transport_request',target_request_id,trim(details),jsonb_build_object('exception_id',result,'type',exception_kind));return result;end;$exception$;
create or replace function public.resolve_trip_exception(target_exception_id uuid,resolution_note text) returns void language plpgsql security invoker set search_path='' as $resolve$
declare e public.exceptions%rowtype;provider uuid;
begin if not(public.has_platform_role('afos_operations') or public.has_platform_role('afos_administrator')) then raise exception 'Not authorized';end if;if char_length(trim(resolution_note))<5 then raise exception 'Resolution required';end if;select * into e from public.exceptions where id=target_exception_id for update;if e.status<>'open' then raise exception 'Exception is not open';end if;select provider_id into provider from public.trips where id=e.trip_id;update public.exceptions set status='resolved',resolution=trim(resolution_note),resolved_by=auth.uid(),resolved_at=now() where id=target_exception_id;insert into public.audit_events(actor_id,organization_id,action,entity_type,entity_id,reason,after_data) values(auth.uid(),provider,'trip.exception_resolved','transport_request',e.request_id,trim(resolution_note),jsonb_build_object('exception_id',e.id));end;$resolve$;

create or replace function public.complete_trip_delivery(target_trip_id uuid,recipient_name text,delivery_time timestamptz,evidence_storage_path text,delivery_note text default '') returns void language plpgsql security invoker set search_path='' as $delivery$
declare t public.trips%rowtype;request_id uuid;
begin if not(public.has_platform_role('afos_operations') or public.has_platform_role('afos_administrator')) then raise exception 'Not authorized';end if;select * into t from public.trips where id=target_trip_id for update;select request_id into request_id from public.allocations where id=t.allocation_id;if t.status<>'at_destination' then raise exception 'Trip must be at destination';end if;if exists(select 1 from public.exceptions where trip_id=target_trip_id and status='open') then raise exception 'Open exceptions must be resolved';end if;if char_length(trim(recipient_name))<2 or char_length(trim(evidence_storage_path))<5 then raise exception 'Delivery evidence incomplete';end if;insert into public.deliveries(trip_id,outcome,delivered_at,evidence_path,recipient_name,submitted_by,confirmed_by,confirmed_at,outcome_reason) values(target_trip_id,'completed',delivery_time,trim(evidence_storage_path),trim(recipient_name),auth.uid(),auth.uid(),now(),nullif(trim(delivery_note),''));update public.trips set status='completed',delivered_at=delivery_time,completed_at=now() where id=target_trip_id;insert into public.trip_status_events(trip_id,from_status,to_status,notes,changed_by) values(target_trip_id,t.status,'completed',coalesce(nullif(trim(delivery_note),''),'Delivery confirmed with evidence'),auth.uid());update public.transport_requests set status='completed',updated_at=now() where id=request_id;insert into public.audit_events(actor_id,organization_id,action,entity_type,entity_id,reason,after_data) values(auth.uid(),t.provider_id,'delivery.completed','transport_request',request_id,nullif(trim(delivery_note),''),jsonb_build_object('trip_id',target_trip_id,'recipient',trim(recipient_name),'delivered_at',delivery_time));end;$delivery$;

grant execute on function public.create_trip_for_company_assignment(uuid,uuid,uuid,uuid,timestamptz,timestamptz) to authenticated;grant execute on function public.advance_trip_status(uuid,text,text) to authenticated;grant execute on function public.report_trip_exception(uuid,uuid,text,text,text,boolean) to authenticated;grant execute on function public.resolve_trip_exception(uuid,text) to authenticated;grant execute on function public.complete_trip_delivery(uuid,text,timestamptz,text,text) to authenticated;
create or replace function public.track_guest_request(request_reference text,tracking_token text) returns jsonb language plpgsql security definer set search_path='' as $track$
declare result jsonb;begin select jsonb_build_object('reference',r.reference,'status',r.status,'container_size',r.container_size,'quantity',r.quantity,'pickup',r.pickup_location,'destination',r.destination_location,'required_at',r.required_at,'estimated_price',r.estimated_price,'price_status',r.price_status,'provider',o.name,'trip_reference',t.reference,'trip_status',t.status,'scheduled_start',t.scheduled_start,'scheduled_end',t.scheduled_end,'delivered_at',t.delivered_at,'delivery_recipient',d.recipient_name,'open_exception',ex.exception_type,'trip_events',coalesce((select jsonb_agg(jsonb_build_object('status',e.to_status,'notes',e.notes,'occurred_at',e.occurred_at) order by e.occurred_at) from public.trip_status_events e where e.trip_id=t.id),'[]'::jsonb)) into result from public.transport_requests r left join public.company_assignments a on a.request_id=r.id left join public.organizations o on o.id=a.provider_id left join public.allocations al on al.request_id=r.id left join public.trips t on t.allocation_id=al.id left join public.deliveries d on d.trip_id=t.id left join lateral(select exception_type from public.exceptions where trip_id=t.id and status='open' order by reported_at desc limit 1) ex on true where upper(r.reference)=upper(trim(request_reference)) and r.tracking_token_hash=encode(extensions.digest(tracking_token,'sha256'),'hex') limit 1;return result;end;$track$;grant execute on function public.track_guest_request(text,text) to anon,authenticated;
commit;
