begin;
create or replace function public.provider_fleet_match_options(target_request_id uuid) returns table(provider_id uuid,provider_name text,available_units integer,total_units integer,match_status text,unavailable_reason text,next_available_at timestamptz) language plpgsql security invoker set search_path='' as $match_options$
declare req public.transport_requests%rowtype;p record;truck_total integer;trailer_total integer;truck_available integer;trailer_available integer;units integer;next_date timestamptz;
begin if not(public.has_platform_role('afos_operations') or public.has_platform_role('afos_administrator')) then raise exception 'Not authorized';end if;select * into req from public.transport_requests where id=target_request_id;if req.id is null then raise exception 'Request not found';end if;
for p in select o.id,o.name from public.organizations o join public.provider_verifications pv on pv.provider_id=o.id where o.organization_type='transport_provider' and pv.status='verified' order by o.name loop
select count(*)::integer,count(*) filter(where t.status='active' and (t.unavailable_until is null or t.unavailable_until<req.required_at::date) and (t.insurance_expires_on is null or t.insurance_expires_on>=req.required_at::date) and (t.roadworthiness_expires_on is null or t.roadworthiness_expires_on>=req.required_at::date) and not exists(select 1 from public.trips x where x.truck_id=t.id and x.status not in('completed','failed','cancelled') and tstzrange(x.scheduled_start,x.scheduled_end,'[)')&&tstzrange(req.required_at,req.required_at+interval '1 day','[)')))::integer into truck_total,truck_available from public.trucks t where t.provider_id=p.id;
select count(*) filter(where lower(trim(t.container_size))=lower(trim(req.container_size)))::integer,count(*) filter(where lower(trim(t.container_size))=lower(trim(req.container_size)) and t.status='active' and (t.unavailable_until is null or t.unavailable_until<req.required_at::date) and (t.insurance_expires_on is null or t.insurance_expires_on>=req.required_at::date) and (t.roadworthiness_expires_on is null or t.roadworthiness_expires_on>=req.required_at::date) and not exists(select 1 from public.trips x where x.trailer_id=t.id and x.status not in('completed','failed','cancelled') and tstzrange(x.scheduled_start,x.scheduled_end,'[)')&&tstzrange(req.required_at,req.required_at+interval '1 day','[)')))::integer into trailer_total,trailer_available from public.trailers t where t.provider_id=p.id;
units:=least(truck_available,trailer_available);next_date:=null;if units<req.quantity then select min(candidate) into next_date from(select x.scheduled_end candidate from public.trips x where x.provider_id=p.id and x.status not in('completed','failed','cancelled') and x.scheduled_end>req.required_at union all select t.unavailable_until::timestamptz from public.trucks t where t.provider_id=p.id and t.unavailable_until>=req.required_at::date union all select t.unavailable_until::timestamptz from public.trailers t where t.provider_id=p.id and lower(trim(t.container_size))=lower(trim(req.container_size)) and t.unavailable_until>=req.required_at::date) dates;end if;
provider_id:=p.id;provider_name:=p.name;available_units:=units;total_units:=least(truck_total,trailer_total);next_available_at:=next_date;if units>=req.quantity then match_status:='available';unavailable_reason:=null;elsif truck_total=0 then match_status:='unavailable';unavailable_reason:='No registered truck';elsif trailer_total=0 then match_status:='unavailable';unavailable_reason:='No compatible '||req.container_size||' trailer';elsif next_date is not null then match_status:='available_later';unavailable_reason:='Vehicles are engaged or temporarily unavailable';else match_status:='unavailable';unavailable_reason:='Not enough active vehicles with valid documents';end if;return next;end loop;end;$match_options$;
grant execute on function public.provider_fleet_match_options(uuid) to authenticated;
commit;
