begin;

alter table public.company_assignments drop constraint if exists company_assignments_request_id_key;
create unique index if not exists company_assignments_active_provider on public.company_assignments(request_id,provider_id) where status<>'cancelled';
alter table public.organizations add column if not exists declared_truck_count integer check(declared_truck_count is null or declared_truck_count>=0);
alter table public.organizations add column if not exists declared_trailer_count integer check(declared_trailer_count is null or declared_trailer_count>=0);
update public.organizations set declared_truck_count=coalesce(declared_truck_count,declared_vehicle_count,0),declared_trailer_count=coalesce(declared_trailer_count,0) where organization_type='transport_provider';

create or replace function public.create_transport_provider_v3(provider_name text,provider_kind text,registration_number text,contact_name text,contact_phone text,contact_email text,declared_trucks integer,declared_trailers integer,operating_areas text) returns uuid language plpgsql security invoker set search_path='' as $provider$
declare result uuid;begin
if not(public.has_platform_role('afos_operations') or public.has_platform_role('afos_administrator')) then raise exception 'Not authorized';end if;
if provider_kind not in('company','individual_owner') or char_length(trim(provider_name))<2 or char_length(trim(contact_name))<2 or char_length(trim(contact_phone))<5 or declared_trucks<0 or declared_trailers<0 or declared_trucks+declared_trailers<1 then raise exception 'Provider details incomplete';end if;
if provider_kind='company' and char_length(trim(registration_number))<2 then raise exception 'Company registration number required';end if;
insert into public.organizations(name,organization_type,registration_number,primary_contact_name,primary_contact_phone,primary_contact_email,provider_kind,declared_vehicle_count,declared_truck_count,declared_trailer_count,operating_areas) values(trim(provider_name),'transport_provider',nullif(trim(registration_number),''),trim(contact_name),trim(contact_phone),nullif(trim(contact_email),''),provider_kind,declared_trucks,declared_trucks,declared_trailers,nullif(trim(operating_areas),'')) returning id into result;
insert into public.provider_verifications(provider_id,status) values(result,'draft');insert into public.audit_events(actor_id,organization_id,action,entity_type,entity_id,after_data) values(auth.uid(),result,'provider.created','organization',result,jsonb_build_object('kind',provider_kind,'declared_trucks',declared_trucks,'declared_trailers',declared_trailers));return result;end;$provider$;

create or replace function public.register_provider_driver(target_provider_id uuid,driver_name text,driver_phone text,license text,license_expiry date) returns uuid language plpgsql security invoker set search_path='' as $driver$
declare result uuid;begin if not(public.has_platform_role('afos_operations') or public.has_platform_role('afos_administrator')) then raise exception 'Not authorized';end if;if char_length(trim(driver_name))<2 or char_length(trim(driver_phone))<5 or char_length(trim(license))<2 then raise exception 'Driver details incomplete';end if;if not exists(select 1 from public.organizations where id=target_provider_id and organization_type='transport_provider') then raise exception 'Provider not found';end if;insert into public.drivers(provider_id,full_name,phone,license_number,license_expires_on) values(target_provider_id,trim(driver_name),trim(driver_phone),upper(trim(license)),license_expiry) returning id into result;insert into public.audit_events(actor_id,organization_id,action,entity_type,entity_id,after_data) values(auth.uid(),target_provider_id,'driver.registered','driver',result,jsonb_build_object('license',upper(trim(license))));return result;end;$driver$;

create or replace function public.available_fleet_pairs(target_request_id uuid,target_provider_id uuid,check_start timestamptz default null,check_end timestamptz default null)
returns table(truck_id uuid,truck_registration text,trailer_id uuid,trailer_registration text,driver_id uuid,driver_name text,available_at timestamptz) language plpgsql security invoker set search_path='' as $pairs$
declare req public.transport_requests%rowtype;starts timestamptz;ends timestamptz;begin
if not(public.has_platform_role('afos_operations') or public.has_platform_role('afos_administrator')) then raise exception 'Not authorized';end if;select * into req from public.transport_requests where id=target_request_id;if req.id is null then raise exception 'Request not found';end if;starts:=coalesce(check_start,req.required_at);ends:=coalesce(check_end,starts+interval'1 day');if ends<=starts then raise exception 'Schedule is invalid';end if;
return query with free_trucks as(select t.id,t.registration_number,row_number()over(order by t.registration_number) n from public.trucks t where t.provider_id=target_provider_id and t.status='active' and (t.unavailable_until is null or t.unavailable_until<starts::date) and (t.insurance_expires_on is null or t.insurance_expires_on>=ends::date) and (t.roadworthiness_expires_on is null or t.roadworthiness_expires_on>=ends::date) and not exists(select 1 from public.trips x where x.truck_id=t.id and x.status not in('completed','failed','cancelled') and tstzrange(x.scheduled_start,x.scheduled_end,'[)')&&tstzrange(starts,ends,'[)'))),free_trailers as(select t.id,t.registration_number,row_number()over(order by t.registration_number) n from public.trailers t where t.provider_id=target_provider_id and t.status='active' and lower(trim(t.container_size))=lower(trim(req.container_size)) and (t.unavailable_until is null or t.unavailable_until<starts::date) and (t.insurance_expires_on is null or t.insurance_expires_on>=ends::date) and (t.roadworthiness_expires_on is null or t.roadworthiness_expires_on>=ends::date) and not exists(select 1 from public.trips x where x.trailer_id=t.id and x.status not in('completed','failed','cancelled') and tstzrange(x.scheduled_start,x.scheduled_end,'[)')&&tstzrange(starts,ends,'[)'))),free_drivers as(select d.id,d.full_name,row_number()over(order by d.full_name) n from public.drivers d where d.provider_id=target_provider_id and d.status='active' and (d.license_expires_on is null or d.license_expires_on>=ends::date) and not exists(select 1 from public.trips x where x.driver_id=d.id and x.status not in('completed','failed','cancelled') and tstzrange(x.scheduled_start,x.scheduled_end,'[)')&&tstzrange(starts,ends,'[)'))) select a.id,a.registration_number,b.id,b.registration_number,c.id,c.full_name,starts from free_trucks a join free_trailers b using(n) join free_drivers c using(n) order by a.n;end;$pairs$;

create or replace function public.assign_request_fleet(target_request_id uuid,selections jsonb,scheduled_start timestamptz,scheduled_end timestamptz,allow_partial boolean default false) returns jsonb language plpgsql security invoker set search_path='' as $assign$
declare req public.transport_requests%rowtype;s jsonb;provider uuid;truck uuid;trailer uuid;driver uuid;assignment uuid;offer uuid;allocation uuid;trip uuid;assigned integer:=0;existing integer;needed integer;begin
if not(public.has_platform_role('afos_operations') or public.has_platform_role('afos_administrator')) then raise exception 'Not authorized';end if;if scheduled_end<=scheduled_start then raise exception 'Schedule is invalid';end if;select * into req from public.transport_requests where id=target_request_id for update;if req.id is null then raise exception 'Request not found';end if;select count(*) into existing from public.trips t join public.allocations a on a.id=t.allocation_id where a.request_id=req.id and t.status not in('failed','cancelled');needed:=greatest(req.quantity-existing,0);if needed=0 then raise exception 'This request already has all required fleet assigned';end if;if jsonb_typeof(selections)<>'array' or jsonb_array_length(selections)=0 then raise exception 'Select at least one fleet unit';end if;if jsonb_array_length(selections)>needed then raise exception 'Too many fleet units selected';end if;if not allow_partial and jsonb_array_length(selections)<>needed then raise exception 'Select exactly the remaining requested fleet units or explicitly allow partial assignment';end if;
for s in select * from jsonb_array_elements(selections) loop provider:=(s->>'provider_id')::uuid;truck:=(s->>'truck_id')::uuid;trailer:=(s->>'trailer_id')::uuid;driver:=(s->>'driver_id')::uuid;perform pg_advisory_xact_lock(hashtextextended(truck::text,0));perform pg_advisory_xact_lock(hashtextextended(trailer::text,0));perform pg_advisory_xact_lock(hashtextextended(driver::text,0));if not exists(select 1 from public.provider_verifications where provider_id=provider and status='verified') then raise exception 'Provider is not verified';end if;if not exists(select 1 from public.available_fleet_pairs(target_request_id,provider,scheduled_start,scheduled_end) p where p.truck_id=truck and p.trailer_id=trailer and p.driver_id=driver) then raise exception 'A selected fleet unit is no longer available';end if;
insert into public.company_assignments(request_id,provider_id,assigned_by,status) values(req.id,provider,auth.uid(),'assigned') on conflict(request_id,provider_id)where status<>'cancelled' do update set assigned_at=now() returning id into assignment;insert into public.provider_offers(request_id,provider_id,quantity,status,sent_at,responded_at,expires_at,created_by) values(req.id,provider,1,'accepted',now(),now(),scheduled_start,auth.uid()) returning id into offer;insert into public.allocations(request_id,offer_id,provider_id,quantity,allocated_by) values(req.id,offer,provider,1,auth.uid()) returning id into allocation;insert into public.trips(reference,allocation_id,provider_id,truck_id,trailer_id,driver_id,scheduled_start,scheduled_end) values('TRIP-'||to_char(now(),'YYMMDD')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,6)),allocation,provider,truck,trailer,driver,scheduled_start,scheduled_end) returning id into trip;insert into public.trip_status_events(trip_id,to_status,notes,changed_by) values(trip,'assigned','Fleet assigned from customer request',auth.uid());assigned:=assigned+1;end loop;
update public.transport_requests set status=case when existing+assigned>=req.quantity then'allocated'::public.request_status else'partially_matched'::public.request_status end,availability_status='available',updated_at=now() where id=req.id;insert into public.audit_events(actor_id,action,entity_type,entity_id,after_data) values(auth.uid(),'request.fleet_assigned','transport_request',req.id,jsonb_build_object('assigned_now',assigned,'assigned_total',existing+assigned,'requested_units',req.quantity));return jsonb_build_object('assigned_now',assigned,'assigned_total',existing+assigned,'requested_units',req.quantity);end;$assign$;

grant execute on function public.create_transport_provider_v3(text,text,text,text,text,text,integer,integer,text) to authenticated;
grant execute on function public.register_provider_driver(uuid,text,text,text,date) to authenticated;
grant execute on function public.available_fleet_pairs(uuid,uuid,timestamptz,timestamptz) to authenticated;
grant execute on function public.assign_request_fleet(uuid,jsonb,timestamptz,timestamptz,boolean) to authenticated;
commit;
